ams:
    build: .
    domainname: ams.dev
    hostname: mediaserver
    working_dir: /opt/adobe/ams/webroot
    volumes:
        - "/hdda/hdda_home/fms_webroot:/opt/adobe/ams/webroot"
    ports:
        - "1935:1935"
        - "1111:1111"
        - "443:443"
        - "80:80"
    cap_add:
        - SYS_PTRACE
